### ISSUE TITLE
Ask for help

### ISSUE THREAD

**Issue by wjx-1999** [cuhk-eda/dr-cu#1]
Hello, I want to ask for your help. Under what circumstances will appear "has the route guide detached from others", cause the program to stop running
![20190821095604](https://user-images.githubusercontent.com/51050307/63396574-17337780-c3fa-11e9-9ff2-a1a92667c69f.png)

**Comment by Rholais** [comment]
The aforementioned warning message `FAIL_DETACHED_GUIDE` is because of disconnected guides for those nets, i.e., the pins cannot be connected by on-track routing only.

**Comment by wjx-1999** [comment]
> The aforementioned warning message `FAIL_DETACHED_GUIDE` is because of disconnected guides for those nets, i.e., the pins cannot be connected by on-track routing only.

**Comment by wjx-1999** [comment]
Thanks!
Does this warning have a significant impact on routing results? So how do I solve this problem? Should I change the guide file or others?

**Comment by chengengjie** [comment]
The detailed router will still find a solution because it will try to expand the routing region a little bit and it will also consider wrong-way edges. But it is preferred that you route guides are better connected (with on-track routing).

**Comment by wjx-1999** [comment]
Thank you!
