### ISSUE TITLE
segmentation fault on an input

### ISSUE THREAD

**Issue by Michael-JY-He** [cuhk-eda/dr-cu#4]
Hi,

I got a segmentation fault during initialization while running on the attached inputs. Can you please take a look? Probably it is an issue in the input.

[out.zip](https://github.com/cuhk-eda/dr-cu/files/4028967/out.zip)

**Comment by Rholais** [comment]
The reason is that there is no `PARALLELRUNLENGTH` spacing table in the LEF file.
I have updated the code by making use of the default spacing to handle this case.

**Comment by Rholais** [comment]
@Michael-JY-He I will close the issue if there is no other problem regarding `PARALLELRUNLENGTH`.
