### ISSUE TITLE
/usr/bin/time: cannot run ./ispd19dr: No such file or directory

### ISSUE THREAD

**Issue by hyli-research** [cuhk-eda/dr-cu#5]
I run "./run.py 8s -p ../toys/" in "run" directory after building, then i have this error " /usr/bin/time: cannot run ./ispd19dr: No such file or directory".
  The file "ispd19dr" is in the “run” directory. how to solve this problem. thank you!

**Comment by Rholais** [comment]
I modified the directory of the toy case.
Can you try it out again?
Please attach the full log from `run.py` to help diagnose if it is still not working.

**Comment by hyli-research** [comment]
still not working... here is the log from run.py
mkdir -p run0612
The following benchmarks will be ran:  [ispd18_sample]
mkdir -p run0612/8s
/usr/bin/time -v ./ispd19dr -lef ../toys//ispd2018/ispd18_sample/ispd18_sample.input.lef -def ../toys//ispd2018/ispd18_sample/ispd18_sample.input.def -guide ../toys//ispd2018/ispd18_sample/ispd18_sample.input.guide -threads 8 -tat 2000000000 -output ispd18_sample.solution.def |& tee ispd18_sample.log
/usr/bin/time: cannot run ./ispd19dr: No such file or directory
Command exited with non-zero status 127
        Command being timed: "./ispd19dr -lef ../toys//ispd2018/ispd18_sample/ispd18_sample.input.lef -def ../toys//ispd2018/ispd18_sample/ispd18_sample.input.def -guide ../toys//ispd2018/ispd18_sample/ispd18_sample.input.guide -threads 8 -tat 2000000000 -output ispd18_sample.solution.def"
        User time (seconds): 0.00
        System time (seconds): 0.00
        Percent of CPU this job got: ?%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.00
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 1180
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 28
        Voluntary context switches: 6
        Involuntary context switches: 1
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 127
mv *.solution.def* *.log *.gprof *.pdf run0612/8s 2>/dev/null

**Comment by jordanpui** [comment]
did you make it excutable?

**Comment by Rholais** [comment]
> still not working... here is the log from run.py
> mkdir -p run0612
> The following benchmarks will be ran: [ispd18_sample]
> mkdir -p run0612/8s
> /usr/bin/time -v ./ispd19dr -lef ../toys//ispd2018/ispd18_sample/ispd18_sample.input.lef -def ../toys//ispd2018/ispd18_sample/ispd18_sample.input.def -guide ../toys//ispd2018/ispd18_sample/ispd18_sample.input.guide -threads 8 -tat 2000000000 -output ispd18_sample.solution.def |& tee ispd18_sample.log
> /usr/bin/time: cannot run ./ispd19dr: No such file or directory
> Command exited with non-zero status 127
> Command being timed: "./ispd19dr -lef ../toys//ispd2018/ispd18_sample/ispd18_sample.input.lef -def ../toys//ispd2018/ispd18_sample/ispd18_sample.input.def -guide ../toys//ispd2018/ispd18_sample/ispd18_sample.input.guide -threads 8 -tat 2000000000 -output ispd18_sample.solution.def"
> User time (seconds): 0.00
> System time (seconds): 0.00
> Percent of CPU this job got: ?%
> Elapsed (wall clock) time (h:mm:ss or m:ss): 0:00.00
> Average shared text size (kbytes): 0
> Average unshared data size (kbytes): 0
> Average stack size (kbytes): 0
> Average total size (kbytes): 0
> Maximum resident set size (kbytes): 1180
> Average resident set size (kbytes): 0
> Major (requiring I/O) page faults: 0
> Minor (reclaiming a frame) page faults: 28
> Voluntary context switches: 6
> Involuntary context switches: 1
> Swaps: 0
> File system inputs: 0
> File system outputs: 0
> Socket messages sent: 0
> Socket messages received: 0
> Signals delivered: 0
> Page size (bytes): 4096
> Exit status: 127
> mv _.solution.def_ *.log *.gprof *.pdf run0612/8s 2>/dev/null

@491913145 Can you try if any of the following commands can work in that directory?
> /usr/bin/time -v ./ispd19dr -lef ../toys/ispd2018/ispd18_sample/ispd18_sample.input.lef -def ../toys/ispd2018/ispd18_sample/ispd18_sample.input.def -guide ../toys/ispd2018/ispd18_sample/ispd18_sample.input.guide -threads 8 -tat 2000000000 -output ispd18_sample.solution.def
> ./ispd19dr -lef ../toys/ispd2018/ispd18_sample/ispd18_sample.input.lef -def ../toys/ispd2018/ispd18_sample/ispd18_sample.input.def -guide ../toys/ispd2018/ispd18_sample/ispd18_sample.input.guide -threads 8 -tat 2000000000 -output ispd18_sample.solution.def

**Comment by Rholais** [comment]
@491913145  I will close the issue if there is no other problem regarding `run.py`.

**Comment by Rholais** [comment]
@491913145 I will close the issue as there is no other problem regarding `run.py`.

**Comment by jiang-yuan** [comment]
> I run "./run.py 8s -p ../toys/" in "run" directory after building, then i have this error " /usr/bin/time: cannot run ./ispd19dr: No such file or directory". The file "ispd19dr" is in the “run” directory. how to solve this problem. thank you!

Hi, I meet the same prolbem after successful build. Could you tell me how you solve this problem?
