### ISSUE TITLE
 Command terminated by signal 11

### ISSUE THREAD

**Issue by EthanPan233** [cuhk-eda/dr-cu#6]
The code doesn't work on several benchmarks, like 9s3, 9t4, 9t6... The error was "Command terminated by signal 11"

**Comment by Rholais** [comment]
Can you share your command and log of `9s3`?

**Comment by EthanPan233** [comment]
> Can you share your command and log of `9s3`?

I can run it on my laptop, but can't run it on my server. I'm using the same code (git clone from this repo), same compiler (gcc9.3) and same version of CMake. The only difference is the CMakeLists.txt. I modified BOOST_ROOT on server. The error was signal 11, and I've located it at MazeRouting::run(). I don't know why the same code performs differently on different machines, do you think this might be because the boost version doesn't match? I'm using boost1.66.

The command is:

`./run.py 9s3 -p ../toys`

the log is like:

mkdir -p run0325
The following benchmarks will be ran:  [ispd19_sample3]
mkdir -p run0325/9s3
/usr/bin/time -v ./ispd19dr -lef ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.lef -def ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.def -guide ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.guide -threads 8 -tat 2000000000 -output ispd19_sample3.solution.def |& tee ispd19_sample3.log
[   0.003] ------------------------------------------------------------------------------
[   0.011]                     ISPD 2019 - Detailed Routing Contest
[   0.011]                              Team number : 15
[   0.011]                              Team name: Dr. CU
[   0.011]         Members: Gengjie Chen, Haocheng Li, Bentian Jiang, Jingsong Chen,
[   0.011]                  Evangeline F.Y. Young
[   0.011]         Affiliation: The Chinese University of Hong Kong
[   0.011] ------------------------------------------------------------------------------
[   0.013] Input .lef file   : ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.lef
[   0.013] Input .def file.  : ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.def
[   0.013] Input .guide file : ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.guide
[   0.013] # of threads      : 8
[   0.014] Runtime limit (sec): 2000000000
[   0.014] Output file name  : ispd19_sample3.solution.def
[   0.014]
[   8.952]
[   9.007] Finish initializing database
[   9.007] MEM: cur=449.633MB, peak=449.633MB
[   9.007]
[   9.007]
[   9.007] ################################################################
[   9.007] Start RRR iteration 0
[   9.007]
[  10.002]
[  10.002] Finish RRR iteration 0
[  10.002] MEM: cur=551.781MB, peak=552.434MB
[  10.003]
[  10.003] ################################################################
[  10.003] Start RRR iteration 1
[  10.003]
[  11.633]
[  11.633] Finish RRR iteration 1
[  11.633] MEM: cur=588.078MB, peak=588.816MB
[  11.633]
[  11.633] ################################################################
[  11.633] Start RRR iteration 2
[  11.633]
[  14.815]
[  14.815] Finish RRR iteration 2
[  14.815] MEM: cur=625.586MB, peak=631.355MB
[  14.815]
[  14.815] ################################################################
[  14.815] Start RRR iteration 3
[  14.815]
[  21.096]
[  21.096] Finish RRR iteration 3
[  21.096] MEM: cur=630.121MB, peak=697.711MB
[  21.096]
[  21.096] ################################################################
[  21.096] Start RRR iteration 4
[  21.096]
Command terminated by signal 11
        Command being timed: "./ispd19dr -lef ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.lef -def ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.def -guide ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.guide -threads 8 -tat 2000000000 -output ispd19_sample3.solution.def"
        User time (seconds): 40.03
        System time (seconds): 1.00
        Percent of CPU this job got: 158%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 0:25.83
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 775648
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 8
        Minor (reclaiming a frame) page faults: 566949
        Voluntary context switches: 509
        Involuntary context switches: 407
        Swaps: 0
        File system inputs: 34144
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 0
mv *.solution.def* *.log *.gprof *.pdf run0325/9s3 2>/dev/null

**Comment by Rholais** [comment]
> > Can you share your command and log of `9s3`?
> 
> I can run it on my laptop, but can't run it on my server. I'm using the same code (git clone from this repo), same compiler (gcc9.3), and same version of CMake. The only difference is the CMakeLists.txt. I modified BOOST_ROOT on the server. The error was signal 11, and I've located it at MazeRouting::run(). I don't know why the same code performs differently on different machines, do you think this might be because the boost version doesn't match? I'm using boost1.66.
> 
> The command is:
> 
> `./run.py 9s3 -p ../toys`
> 
> the log is like:
> 
> mkdir -p run0325
> The following benchmarks will be ran: [ispd19_sample3]
> mkdir -p run0325/9s3
> /usr/bin/time -v ./ispd19dr -lef ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.lef -def ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.def -guide ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.guide -threads 8 -tat 2000000000 -output ispd19_sample3.solution.def |& tee ispd19_sample3.log
> [ 0.003] ------------------------------------------------------------------------------
> [ 0.011] ISPD 2019 - Detailed Routing Contest
> [ 0.011] Team number : 15
> [ 0.011] Team name: Dr. CU
> [ 0.011] Members: Gengjie Chen, Haocheng Li, Bentian Jiang, Jingsong Chen,
> [ 0.011] Evangeline F.Y. Young
> [ 0.011] Affiliation: The Chinese University of Hong Kong
> [ 0.011] ------------------------------------------------------------------------------
> [ 0.013] Input .lef file : ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.lef
> [ 0.013] Input .def file. : ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.def
> [ 0.013] Input .guide file : ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.guide
> [ 0.013] # of threads : 8
> [ 0.014] Runtime limit (sec): 2000000000
> [ 0.014] Output file name : ispd19_sample3.solution.def
> [ 0.014]
> [ 8.952]
> [ 9.007] Finish initializing database
> [ 9.007] MEM: cur=449.633MB, peak=449.633MB
> [ 9.007]
> [ 9.007]
> [ 9.007] ################################################################
> [ 9.007] Start RRR iteration 0
> [ 9.007]
> [ 10.002]
> [ 10.002] Finish RRR iteration 0
> [ 10.002] MEM: cur=551.781MB, peak=552.434MB
> [ 10.003]
> [ 10.003] ################################################################
> [ 10.003] Start RRR iteration 1
> [ 10.003]
> [ 11.633]
> [ 11.633] Finish RRR iteration 1
> [ 11.633] MEM: cur=588.078MB, peak=588.816MB
> [ 11.633]
> [ 11.633] ################################################################
> [ 11.633] Start RRR iteration 2
> [ 11.633]
> [ 14.815]
> [ 14.815] Finish RRR iteration 2
> [ 14.815] MEM: cur=625.586MB, peak=631.355MB
> [ 14.815]
> [ 14.815] ################################################################
> [ 14.815] Start RRR iteration 3
> [ 14.815]
> [ 21.096]
> [ 21.096] Finish RRR iteration 3
> [ 21.096] MEM: cur=630.121MB, peak=697.711MB
> [ 21.096]
> [ 21.096] ################################################################
> [ 21.096] Start RRR iteration 4
> [ 21.096]
> Command terminated by signal 11
> Command being timed: "./ispd19dr -lef ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.lef -def ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.def -guide ../toys/ispd2019/ispd19_sample3/ispd19_sample3.input.guide -threads 8 -tat 2000000000 -output ispd19_sample3.solution.def"
> User time (seconds): 40.03
> System time (seconds): 1.00
> Percent of CPU this job got: 158%
> Elapsed (wall clock) time (h:mm:ss or m:ss): 0:25.83
> Average shared text size (kbytes): 0
> Average unshared data size (kbytes): 0
> Average stack size (kbytes): 0
> Average total size (kbytes): 0
> Maximum resident set size (kbytes): 775648
> Average resident set size (kbytes): 0
> Major (requiring I/O) page faults: 8
> Minor (reclaiming a frame) page faults: 566949
> Voluntary context switches: 509
> Involuntary context switches: 407
> Swaps: 0
> File system inputs: 34144
> File system outputs: 0
> Socket messages sent: 0
> Socket messages received: 0
> Signals delivered: 0
> Page size (bytes): 4096
> Exit status: 0
> mv _.solution.def_ *.log *.gprof *.pdf run0325/9s3 2>/dev/null

Can you try running a debug build with gdb to see how it crashes?
```bash
scripts/build.py -o debug
```
If it crashes inside `boost`, please consider using the same `boost` version as your laptop.

**Comment by Rholais** [comment]
@EthanPan233  I will close the issue if there is no other problem regarding `boost`

**Comment by Rholais** [comment]
@EthanPan233 I will close the issue if there is no other problem regarding `boost`
