### ISSUE TITLE
Failed to build 

### ISSUE THREAD

**Issue by juhonkang** [cuhk-eda/dr-cu#9]
Please add this to make it more robust to errors. Thanks!

for target in build_targets:
    if target != '':
        run('cmake --build {} --target {} -- {}'.format(args.build_dir, target, args.make_options))
    else:
        run('cmake --build {} -- {}'.format(args.build_dir, args.make_options))

**Comment by Rholais** [comment]
Thanks for contributing the enhancement!
Can you help submit a pull request so that we can recognize your contribution?

**Comment by Rholais** [comment]
@juhonkang  I will close the issue if there is no other problem regarding `build_targets`

**Comment by Rholais** [comment]
@juhonkang I will close the issue if there is no other problem regarding `build_targets`
